### ISSUE TITLE
ERROR: Downloaded file 'yolov5n.pt' does not exist or size is < min_bytes=100000.0

### ISSUE THREAD

**Issue by meua** [dora-rs/dora-drives#56] opened 2023-04-24 11:51 UTC
**Describe the bug**
```bash
(dora3.7) jarvis@jia:~/coding/dora_home/dora-drives$ dora start graphs/oasis/oasis_agent_obstacle_location.yaml --attach --hot-reload --name oasis-obstacle
15a16f25-4427-41c0-b4db-5d52d5c70c03
../../carla/carla_source_node.py:77: DeprecationWarning: Call to deprecated method __init__. (Since v1.35, the Jaeger supports OTLP natively. Please use the OTLP exporter instead. Support for this exporter will end July 2023.) -- Deprecated since version 1.16.0.
  agent_port=6831,
Using cache found in /home/jarvis/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2023-4-10 Python-3.7.16 torch-1.13.0+cu117 CUDA:0 (NVIDIA GeForce RTX 3080 Ti, 12042MiB)

Downloading https://github.com/ultralytics/yolov5/releases/download/v0.2.1/yolov5n.pt to yolov5n.pt...
ERROR: HTTP Error 404: Not Found
Re-attempting https://github.com/ultralytics/yolov5/releases/download/v0.2.1/yolov5n.pt to yolov5n.pt...
curl: (7) Failed to receive SOCKS4 connect request ack.

ERROR: Downloaded file 'yolov5n.pt' does not exist or size is < min_bytes=100000.0
yolov5n.pt missing, try downloading from https://github.com/ultralytics/yolov5/releases/v0.2.1

Downloading https://github.com/ultralytics/yolov5/releases/download/v0.2.1/yolov5n.pt to yolov5n.pt...
ERROR: Remote end closed connection without response
Re-attempting https://github.com/ultralytics/yolov5/releases/download/v0.2.1/yolov5n.pt to yolov5n.pt...
curl: (7) Failed to receive SOCKS4 connect request ack.

ERROR: Downloaded file 'yolov5n.pt' does not exist or size is < min_bytes=100000.0
yolov5n.pt missing, try downloading from https://github.com/ultralytics/yolov5/releases/v0.2.1

Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: Dora Runtime raised an error.

Caused by:
   0: main task failed
   1: failed to init an operator
   2: failed to init python operator
   3: Exception: [Errno 2] No such file or directory: 'yolov5n.pt'. Cache may be out of date, try `force_reload=True` or see https://github.com/ultralytics/yolov5/issues/36 for help.Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/home/jarvis/coding/dora_home/dora-drives/operators/yolov5_op.py", line 25, in __init__
          "yolov5n",
        File "/home/jarvis/anaconda3/envs/dora3.7/lib/python3.7/site-packages/torch/hub.py", line 542, in load
          model = _load_local(repo_or_dir, model, *args, **kwargs)
        File "/home/jarvis/anaconda3/envs/dora3.7/lib/python3.7/site-packages/torch/hub.py", line 572, in _load_local
          model = entry(*args, **kwargs)
        File "/home/jarvis/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 88, in yolov5n
          return _create('yolov5n', pretrained, channels, classes, autoshape, _verbose, device)
        File "/home/jarvis/.cache/torch/hub/ultralytics_yolov5_master/hubconf.py", line 78, in _create
          raise Exception(s) from e


Location:
    binaries/runtime/src/operator/python.rs:26:9
```

**To Reproduce**
1. Dora start daemon: `dora up` 
2. Start a new dataflow: `dora start graphs/oasis/oasis_agent_obstacle_location.yaml --attach`

**Expected behavior**

**Screenshots or Video**
![image](https://user-images.githubusercontent.com/11570442/233985764-e1888770-a449-4f7f-91f9-e8bc6e9b1e0c.png)

**Environments (please complete the following information):**
 - System info: ```Linux jia 5.15.0-69-generic #76~20.04.1-Ubuntu SMP Mon Mar 20 15:54:19 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux```
 - Dora version: `0.2.2`

**Comment by haixuanTao** [comment] 2023-04-25 00:05
If you look at the traceback you will see that you had a: `HTTP Error 404: Not Found`

I'm going to close this because it's linked to your network and not our repo directly.

**Closed** 2023-04-25 00:05 UTC

**Comment by meua** [comment] 2023-04-28 03:02
> ```shell
> https://github.com/ultralytics/yolov5/releases/download/v0.2.1/yolov5n.pt
> ```

No, I did not express clearly, `https://github.com/ultralytics/yolov5/releases/download/v0.2.1/yolov5n.pt`, What I want to explain is that this address does not exist.
![image](https://user-images.githubusercontent.com/11570442/235044378-7042267d-0611-49db-b1b6-932eff787fa4.png)

**Comment by haixuanTao** [comment] 2023-04-28 03:26
I see, our CI: https://github.com/dora-rs/dora/actions/runs/4820699396/jobs/8585556778 is passing, so you can maybe try to remove caching home/jarvis/.cache/torch/hub/ultralytics_yolov5_master and see if the issue is solved?

**Comment by meua** [comment] 2023-04-28 06:24
> 
Ok, I'm going to try to fix this by doing something like this.
